[metadata]
name = formapauper-backend
version = 0.1.0
description = Backend service for Form a Pauper

[options]
packages = find:
package_dir = =.
include_package_data = True
install_requires =
    fastapi
    uvicorn[standard]
    sqlmodel
    pydantic-settings
    python-multipart

[options.packages.find]
where = .
